steps:
- id: "Fetching mtapputil" 
  name: gcr.io/cloud-builders/gcloud
  args:
    - source
    - repos
    - clone 
    - moderntrade-common-util
- id: "Building mtapputil and vatcps"
  name: gcr.io/cloud-builders/mvn
  entrypoint: bash
  args:
    - -c
    - |
      mvn -f /workspace/moderntrade-common-util/pom.xml clean install 
      mvn clean install
- id: "Deploying into  mt-application-srv"
  name: gcr.io/cloud-builders/gcloud
  args:
    - compute
    - scp
    - target/vatcps.war
    - mt-application-srv:/home/sftp_user
    - --zone=asia-south1-a
    - --impersonate-service-account=$_SERVICE_ACCOUNT_EMA
- id: "Restarting ${_DEV_APP_VM}"
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
     gcloud compute instances stop  mt-application-srv
     gcloud compute instances start  mt-application-srv
- id: "Creating Image from ${_DEV_APP_VM}"
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    -  |
     current_date=`date '+%Y_%m_%d`
     new_image=`echo $_DEV_APP_VM-image-v$current_date`
     echo $new_image > /workspace/new_image_name.txt
     gcloud compute images create $new_image --source-disk=$_DEV_APP_VM --source-disk-zone=asia-south1-a --storage-location=asia-south1