steps:
- id: "Fetching source" 
  name: gcr.io/cloud-builders/gcloud
  args:
    - source
    - repos
    - clone 
    - moderntrade-common-util
- id: "Building Artifact"
  name: gcr.io/cloud-builders/mvn
  entrypoint: bash
  args:
    - -c
    - |
      mvn -f /workspace/moderntrade-common-util/pom.xml clean install 
      mvn clean install
- id: "Deploying into dev VM"
  name: gcr.io/cloud-builders/gcloud
  args:
    - compute
    - scp
    - target/$_ARTIFACT_NAME
    - $_VM_NAME:/home/sftp_user
    - --zone=$_VM_ZONE
    - --impersonate-service-account=$_SERVICE_ACCOUNT_EMAIL
- id: "Restarting the service in dev VM"
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      gcloud compute ssh $_VM_NAME --zone=$_VM_ZONE --command="kill -9 `ps -ef | grep 'java -jar $_ARTIFACT_NAME' | head -1 | awk '{print $2}'`;nohup java -jar $_ARTIFACT_NAME > $_ARTIFACT_LOG_FILE_NAME &"